name: 'github-govulncheck-action'
author: 'KhulnaSoft DevSec'
branding:
  icon: 'check'
  color: 'blue'
description: 'Scans golang using govulncheck action'
inputs:
  args:
    description: 'Arguments passed to govulncheck'
    required: false
    default: './...'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_ARGS: ${{ inputs.args }}
