name: Release
on: 
  push:
    branches: [ main ]
    tags-ignore:
      - 'v*'
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: docker build .
  release:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUBLISH_TOKEN }} # for pushing to protected branch
      - name: Publish new version
        run: |
          git config --global user.email "116948796+NxPKG@users.noreply.github.com"
          git config --global user.name "Release Bot"
          git tag -fa v1 -m "Update v1 tag"
          git push origin v1 --force
        
